# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Make TJ's Floors Great Again
email: willzhang05@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Students have been leaving trash throughout the school. 
  We need to be responsible members of the TJ community by keeping
  our commons areas and hallways clean before, during, and after lunch.
baseurl: "/tjfloors" # the subpath of your site, e.g. /blog
url: "https://wzhang.me" # the base hostname & protocol for your site
twitter_username: willzhang05
github_username:  willzhang05

# Build settings
markdown: kramdown
